"""Qué mide cada análisis, en palabras simples. Es información general, no un diagnóstico.

Provisional: estos textos deben revisarse con un médico (ver CLAUDE.md). Cada texto dice qué se mide y
para qué se suele pedir; nunca qué significa un resultado concreto de una persona.
"""

from __future__ import annotations

from . import terminology

ABOUT: dict[str, str] = {
    # Glucosa
    "glucose": "El azúcar que circula en la sangre después de varias horas sin comer. Se pide para vigilar cómo el cuerpo maneja el azúcar.",
    "hba1c": "El promedio del azúcar en la sangre de los últimos 2 a 3 meses. A diferencia de la glucosa, no cambia por lo que comiste ayer.",
    "insulin": "La hormona que ayuda a que el azúcar entre a las células. Junto con la glucosa muestra qué tanto esfuerzo hace el cuerpo para controlarla.",
    "homa_ir": "Un cálculo con la glucosa y la insulina en ayunas que estima qué tan bien responde el cuerpo a la insulina.",
    # Lípidos
    "chol_total": "Toda la grasa tipo colesterol que viaja en la sangre (la «buena» y la «mala» juntas).",
    "ldl": "El colesterol «malo»: el que puede acumularse en las paredes de las arterias. Es el principal objetivo al cuidar el corazón.",
    "hdl": "El colesterol «bueno»: recoge colesterol de la sangre y lo lleva al hígado para eliminarlo.",
    "triglycerides": "Un tipo de grasa de la sangre que viene de lo que comes y de lo que el cuerpo fabrica. Sube con azúcares, alcohol y exceso de calorías.",
    "crp_hs": "Una proteína que el hígado produce cuando hay inflamación. La versión ultrasensible detecta inflamación leve y se usa para valorar riesgo cardiovascular.",
    "total_lipids": "La suma de todas las grasas de la sangre. Se calcula a partir de otros resultados.",
    "non_hdl": "Todo el colesterol menos el «bueno». Se calcula restando el HDL al colesterol total.",
    "vldl": "Colesterol que viaja junto con los triglicéridos. Normalmente se calcula a partir de ellos.",
    "chol_hdl_ratio": "Colesterol total dividido entre el «bueno». Resume en un número el equilibrio entre colesterol «malo» y «bueno».",
    "ldl_hdl_ratio": "Colesterol «malo» dividido entre el «bueno». Es un cálculo a partir de otros dos resultados.",
    "tg_hdl_ratio": "Triglicéridos divididos entre colesterol «bueno». Es un cálculo a partir de otros dos resultados.",
    "sd_ldl": "La parte del colesterol «malo» formada por partículas pequeñas y densas, que se meten con más facilidad en las arterias.",
    "phospholipids": "Grasas que forman parte de las membranas de todas las células y que también viajan en la sangre.",
    # Hígado
    "alt": "Una enzima que está sobre todo en el hígado. Si las células del hígado se irritan o dañan, pasa a la sangre.",
    "ast": "Una enzima que está en el hígado, pero también en músculos y corazón. Se interpreta junto con la ALT.",
    "alp": "Una enzima de los conductos de la bilis y de los huesos. Se pide para revisar el flujo de bilis y la salud del hueso.",
    "ggt": "Una enzima del hígado y de los conductos biliares. Es sensible a alcohol, medicamentos y problemas de la vía biliar.",
    "albumin": "La proteína más abundante de la sangre. La fabrica el hígado y ayuda a mantener el líquido dentro de los vasos.",
    "protein_total": "Toda la proteína de la sangre (albúmina y globulinas juntas).",
    "globulin": "Proteínas de la sangre, entre ellas los anticuerpos. Se calcula restando la albúmina a las proteínas totales.",
    "ag_ratio": "Albúmina dividida entre globulinas. Un cálculo a partir de otros resultados.",
    "ast_alt_ratio": "AST dividida entre ALT. Un cálculo a partir de otros dos resultados que se usa para orientar el origen de las enzimas.",
    "ggt_ast_ratio": "GGT dividida entre AST. Un cálculo a partir de otros dos resultados.",
    "bilirubin_total": "El pigmento amarillo que se forma cuando se destruyen los glóbulos rojos viejos. El hígado lo elimina por la bilis.",
    "bilirubin_direct": "La bilirrubina que el hígado ya procesó y está lista para eliminarse en la bilis.",
    "bilirubin_indirect": "La bilirrubina que todavía no pasa por el hígado. Se calcula restando la directa a la total.",
    # Páncreas
    "amylase": "Una enzima que ayuda a digerir los carbohidratos. La producen sobre todo el páncreas y las glándulas salivales.",
    "lipase": "Una enzima del páncreas que ayuda a digerir las grasas. Es más específica del páncreas que la amilasa.",
    "amylase_lipase_ratio": "Amilasa dividida entre lipasa. Un cálculo a partir de otros dos resultados.",
    # Riñón
    "creatinine": "Un desecho que producen los músculos y que los riñones filtran. Se usa para saber qué tan bien filtran los riñones.",
    "bun": "El nitrógeno de la urea en la sangre. La urea es un desecho de las proteínas que eliminan los riñones.",
    "urea": "Un desecho que se forma al usar las proteínas y que eliminan los riñones. Se calcula a partir del BUN.",
    "uric_acid": "Un desecho que se forma al descomponer unas sustancias llamadas purinas. Si se acumula puede formar cristales en articulaciones o riñón.",
    "bun_creat_ratio": "BUN dividido entre creatinina. Un cálculo a partir de otros dos resultados.",
    "egfr": "Una estimación de cuánta sangre filtran los riñones por minuto. Se calcula con la creatinina, la edad y el sexo.",
    "cystatin_c": "Una proteína que se filtra en los riñones. Sirve para valorar el riñón sin depender de la masa muscular, como la creatinina.",
    "egfr_cys": "La misma estimación de filtración del riñón, pero calculada con cistatina C en lugar de creatinina.",
    # Electrolitos
    "sodium": "El principal mineral que regula el agua del cuerpo, los nervios y los músculos.",
    "potassium": "Un mineral clave para el ritmo del corazón y el trabajo de músculos y nervios.",
    "chloride": "Un mineral que acompaña al sodio y ayuda a mantener el equilibrio de líquidos y ácidos del cuerpo.",
    "co2_total": "Refleja el bicarbonato de la sangre, que ayuda a mantener estable su acidez.",
    "calcium": "El mineral de huesos y dientes; también interviene en músculos, nervios y coagulación.",
    "calcium_ionized": "La parte del calcio de la sangre que está libre y activa. Se calcula a partir del calcio total.",
    "phosphorus": "Un mineral que trabaja con el calcio en huesos y en la energía de las células. Lo regulan los riñones.",
    "magnesium": "Un mineral necesario para músculos, nervios y el ritmo del corazón.",
    "osmolality": "Qué tan concentrada está la sangre (cuántas sustancias disueltas lleva). Se calcula con sodio, glucosa y urea.",
    # Sangre
    "hemoglobin": "La proteína de los glóbulos rojos que transporta oxígeno. Es el dato principal para saber si hay anemia.",
    "hematocrit": "El porcentaje de la sangre que son glóbulos rojos.",
    "rbc": "El número de glóbulos rojos, las células que llevan oxígeno por el cuerpo.",
    "wbc": "El número de glóbulos blancos, las células de defensa del cuerpo. Suben con muchas infecciones e inflamaciones.",
    "platelets": "Las células que ayudan a que la sangre coagule y las heridas dejen de sangrar.",
    "mcv": "El tamaño promedio de los glóbulos rojos. Ayuda a averiguar el tipo de anemia, si la hay.",
    "mch": "Cuánta hemoglobina lleva en promedio cada glóbulo rojo.",
    "mchc": "La concentración de hemoglobina dentro de los glóbulos rojos.",
    "rdw": "Qué tan distintos son entre sí los tamaños de los glóbulos rojos.",
    "rdw_sd": "Otra forma de medir qué tan distintos son entre sí los tamaños de los glóbulos rojos.",
    "mpv": "El tamaño promedio de las plaquetas.",
    "ferritin": "La proteína que guarda hierro en el cuerpo. Refleja las reservas de hierro; también sube con inflamación.",
    "iron": "El hierro que circula en la sangre en este momento. Cambia durante el día, por eso se interpreta con la ferritina.",
    "uibc": "Cuánto espacio libre queda en la proteína que transporta hierro (transferrina) para llevar más.",
    "tibc": "La capacidad total de la sangre para transportar hierro. Se calcula sumando el hierro y la capacidad libre.",
    "iron_sat": "Qué porcentaje de la proteína que transporta hierro está realmente cargada. Se calcula a partir de otros resultados.",
    "transferrin": "La proteína que transporta el hierro por la sangre.",
    # Glóbulos blancos
    "neut_pct": "El porcentaje de tus glóbulos blancos que son neutrófilos, las primeras células que combaten las bacterias.",
    "neut_abs": "La cantidad de neutrófilos, las primeras células que combaten las bacterias.",
    "neut_seg_pct": "El porcentaje de glóbulos blancos que son neutrófilos maduros (segmentados), que combaten bacterias.",
    "neut_seg_abs": "La cantidad de neutrófilos maduros (segmentados), que combaten bacterias.",
    "neut_band_pct": "El porcentaje de glóbulos blancos que son neutrófilos jóvenes (en banda). Aumentan cuando el cuerpo pide más defensas.",
    "neut_band_abs": "La cantidad de neutrófilos jóvenes (en banda). Aumentan cuando el cuerpo pide más defensas.",
    "lymph_pct": "El porcentaje de glóbulos blancos que son linfocitos, las células de defensa contra virus y de la memoria inmunológica.",
    "lymph_abs": "La cantidad de linfocitos, las células de defensa contra virus y de la memoria inmunológica.",
    "mono_pct": "El porcentaje de glóbulos blancos que son monocitos, que limpian restos y combaten infecciones prolongadas.",
    "mono_abs": "La cantidad de monocitos, que limpian restos y combaten infecciones prolongadas.",
    "eos_pct": "El porcentaje de glóbulos blancos que son eosinófilos, relacionados con alergias y parásitos.",
    "eos_abs": "La cantidad de eosinófilos, células relacionadas con alergias y parásitos.",
    "baso_pct": "El porcentaje de glóbulos blancos que son basófilos, células que participan en las reacciones alérgicas.",
    "baso_abs": "La cantidad de basófilos, células que participan en las reacciones alérgicas.",
    # Tiroides
    "tsh": "La hormona con la que la hipófisis (en el cerebro) le indica a la tiroides cuánto trabajar. Es la prueba principal para revisar la tiroides.",
    "t4_free": "La hormona principal de la tiroides que está libre y activa en la sangre.",
    "t4_total": "Toda la hormona T4 de la sangre, la libre y la que va unida a proteínas.",
    "t3_free": "La forma activa de la hormona de la tiroides, libre en la sangre.",
    "t3_total": "Toda la hormona T3 de la sangre, la libre y la que va unida a proteínas.",
    "t3_uptake": "Una prueba que ayuda a interpretar las hormonas tiroideas totales según las proteínas que las transportan.",
    "fti": "Un cálculo a partir de la T4 y la captación de T3 que estima la hormona tiroidea libre.",
    "pbi": "El yodo que viaja unido a proteínas, reflejo de las hormonas de la tiroides. Es una prueba poco usada hoy.",
    # Coagulación
    "pt": "Cuántos segundos tarda la sangre en coagular por una de sus vías. Revisa varios factores de coagulación hechos en el hígado.",
    "inr": "El tiempo de protrombina expresado en una escala estándar, para poder comparar entre laboratorios y vigilar anticoagulantes.",
    "aptt": "Cuántos segundos tarda la sangre en coagular por la otra vía principal. Sirve para detectar faltas de factores de coagulación.",
    "tt": "Cuánto tarda en formarse el último paso del coágulo (fibrinógeno a fibrina).",
    "fibrinogen": "La proteína que forma la malla del coágulo. También sube con la inflamación.",
    # Otros y marcadores
    "vitamin_d": "Los niveles de vitamina D, que ayuda al cuerpo a absorber calcio y a mantener huesos y músculos.",
    "igg": "El anticuerpo más abundante; da defensa duradera contra infecciones.",
    "iga": "El anticuerpo que protege las mucosas (intestino, vías respiratorias).",
    "igm": "El primer anticuerpo que el cuerpo produce ante una infección nueva.",
    "cea": "Una proteína que puede aumentar en algunos tumores, pero también con tabaquismo o inflamación. Se usa para dar seguimiento, no para diagnosticar.",
    "psa_total": "Una proteína de la próstata. Puede subir por crecimiento, inflamación o tumores de la próstata.",
    "ldh": "Una enzima que está en casi todos los tejidos; sube cuando hay daño de células en músculo, hígado, sangre y otros.",
    "cpk": "Una enzima de los músculos (y del corazón). Sube después de ejercicio intenso o cuando hay daño muscular.",
    "procalcitonin": "Una sustancia que sube mucho en infecciones graves por bacterias. Ayuda a distinguirlas de las infecciones por virus.",
    "sars_cov2_pcr": "Busca el material genético del virus del COVID-19 en una muestra respiratoria.",
    "hiv_ab": "Busca anticuerpos contra el virus del VIH.",
    "hcv_ab": "Busca anticuerpos contra el virus de la hepatitis C.",
    "vdrl": "Una prueba de detección de sífilis: busca anticuerpos que aparecen con esa infección.",
    "typhoid_o": "Una prueba de anticuerpos contra la Salmonella (fiebre tifoidea), dirigida al antígeno O.",
    "typhoid_h": "Una prueba de anticuerpos contra la Salmonella (fiebre tifoidea), dirigida al antígeno H.",
    "paratyphoid_a": "Una prueba de anticuerpos contra la Salmonella paratyphi A.",
    "paratyphoid_b": "Una prueba de anticuerpos contra la Salmonella paratyphi B.",
    "brucella": "Una prueba de anticuerpos contra la Brucella, la bacteria de la brucelosis (viene de lácteos sin pasteurizar y animales).",
    "proteus_ox19": "Una prueba de anticuerpos que se usa para orientar el diagnóstico de infecciones como el tifo.",
    "mycoplasma_hominis": "Cultivo para saber si crece la bacteria Mycoplasma hominis en una muestra genital.",
    "ureaplasma": "Cultivo para saber si crece la bacteria Ureaplasma urealyticum en una muestra genital.",
    # Heces
    "stool_ph": "La acidez de las heces. Se mide sobre todo cuando se sospecha que no se absorbe bien algún azúcar.",
    "stool_color": "El color de las heces; puede cambiar con la comida, medicamentos, bilis o sangre.",
    "stool_consistency": "Qué tan formadas o líquidas son las heces.",
    "stool_blood": "Si a simple vista hay sangre en las heces.",
    "stool_occult_blood": "Busca sangre en las heces que no se ve a simple vista.",
    "stool_reducing_sugars": "Busca azúcares sin digerir en las heces, que aparecen cuando no se absorben bien algunos azúcares.",
    "stool_food_remains": "Si se ven restos de comida sin digerir en las heces.",
    "stool_mucus": "Si hay moco en las heces, una capa que normalmente protege el intestino.",
    "stool_macro_parasites": "Si se ven a simple vista parásitos o partes de ellos en las heces.",
    "stool_rbc": "Glóbulos rojos vistos en el microscopio en las heces; indican sangrado en el intestino.",
    "stool_wbc": "Glóbulos blancos vistos en el microscopio en las heces; pueden indicar inflamación o infección del intestino.",
    "stool_muscle_fibers": "Fibras de carne sin digerir vistas en el microscopio en las heces.",
    "stool_vegetable_fibers": "Fibras de vegetales vistas en el microscopio en las heces; son normales en la dieta.",
    "stool_epithelial": "Células de la pared del intestino que se desprenden y aparecen en las heces.",
    "stool_micro_parasites": "Parásitos o sus huevos vistos en el microscopio en las heces.",
    "giardia_antigen": "Busca proteínas de Giardia, un parásito del intestino, en las heces.",
    "calprotectin_stool": "Una proteína que sube en las heces cuando hay inflamación en el intestino. Ayuda a distinguirla de problemas sin inflamación.",
    "lactoferrin_stool": "Una proteína de los glóbulos blancos que aparece en las heces cuando hay inflamación en el intestino.",
    # Orina
    "albumin_urine": "La albúmina que se pierde en la orina. Los riñones sanos casi no la dejan pasar.",
    "urine_sg": "Qué tan concentrada está la orina, o sea, qué tan bien los riñones concentran o diluyen.",
    "urine_ph": "La acidez de la orina.",
    "urine_color": "El color de la orina; depende sobre todo de cuánta agua tomaste, y también de alimentos y medicamentos.",
    "urine_appearance": "Si la orina se ve transparente o turbia.",
    "urine_nitrite": "Busca nitritos, que producen algunas bacterias. Ayuda a detectar infección urinaria.",
    "urine_leuk_esterase": "Una enzima de los glóbulos blancos; ayuda a detectar inflamación o infección de vías urinarias.",
    "urine_protein": "Busca proteínas en la orina, que normalmente casi no aparecen.",
    "urine_glucose": "Busca azúcar en la orina, que normalmente no aparece.",
    "urine_ketones": "Busca cetonas, que se forman cuando el cuerpo quema grasa por falta de azúcar (ayuno largo o diabetes descontrolada).",
    "urine_bilirubin": "Busca bilirrubina en la orina, que normalmente no aparece.",
    "urine_urobilinogen": "Una sustancia que se forma en el intestino a partir de la bilirrubina. Se mide para revisar hígado y vías biliares.",
    "urine_blood": "Busca sangre o hemoglobina en la orina, que no se ve a simple vista.",
    "urine_wbc_micro": "Cuántos glóbulos blancos se ven en el microscopio en la orina.",
    "urine_rbc_micro": "Cuántos glóbulos rojos se ven en el microscopio en la orina.",
    "urine_dysmorphic_rbc": "Glóbulos rojos deformes en la orina; ayudan a saber si la sangre viene del riñón.",
    "urine_casts": "Moldes de proteína que se forman en los tubos del riñón y aparecen en la orina.",
    "urine_crystals": "Cristales de minerales en la orina, que pueden ser normales o relacionarse con cálculos.",
    "urine_urate_crystals": "Cristales de urato amorfo; son frecuentes y suelen depender de qué tan ácida y concentrada está la orina.",
    "urine_squamous": "Células de la piel y de la parte final de las vías urinarias; su presencia suele indicar contaminación de la muestra.",
    "urine_transitional": "Células que recubren el interior de la vejiga y los uréteres.",
    "urine_renal_tubular": "Células que recubren los tubos del riñón.",
    "urine_mucus": "Filamentos de moco en la orina; son comunes y suelen ser normales.",
    "urine_bacteria": "Bacterias vistas en el microscopio en la orina.",
    "urine_yeast": "Levaduras (hongos) vistas en el microscopio en la orina.",
    # Semen
    "semen_abstinence": "Los días sin eyacular antes de dar la muestra; influye en el volumen y la concentración.",
    "semen_volume": "La cantidad de semen de la muestra.",
    "semen_viscosity": "Qué tan espeso es el semen.",
    "semen_ph": "La acidez del semen.",
    "semen_conc": "Cuántos espermatozoides hay por mililitro.",
    "semen_total": "El total de espermatozoides de toda la muestra.",
    "semen_prog_motility": "El porcentaje de espermatozoides que avanzan hacia adelante.",
    "semen_nonprog_motility": "El porcentaje de espermatozoides que se mueven pero sin avanzar.",
    "semen_total_motility": "El porcentaje de espermatozoides que se mueven, avancen o no.",
    "semen_immotile": "El porcentaje de espermatozoides que no se mueven.",
    "semen_vitality": "El porcentaje de espermatozoides vivos.",
    "semen_head_abn": "El porcentaje de espermatozoides con la cabeza de forma anormal.",
    "semen_midpiece_abn": "El porcentaje de espermatozoides con la pieza intermedia de forma anormal.",
    "semen_tail_abn": "El porcentaje de espermatozoides con la cola de forma anormal.",
    "semen_cyto_excess": "El porcentaje de espermatozoides con exceso de citoplasma sobrante de su formación.",
    "semen_normal_morph": "El porcentaje de espermatozoides con forma normal.",
    "semen_wbc": "Cuántos glóbulos blancos hay en el semen; pueden indicar inflamación o infección.",
    "semen_appearance": "El aspecto del semen a simple vista.",
    "semen_color": "El color del semen.",
    "semen_liquefaction": "Cuánto tarda el semen en volverse líquido después de la eyaculación.",
    "semen_fructose": "Un azúcar que aportan las vesículas seminales; refleja el funcionamiento de esa glándula.",
    "semen_agglutination": "Si los espermatozoides se pegan entre sí.",
    "semen_immature_cells": "Células jóvenes que aún no son espermatozoides y aparecen en la muestra.",
    "semen_bacteria": "Bacterias vistas en el microscopio en el semen.",
    "semen_rbc": "Glóbulos rojos vistos en el microscopio en el semen.",
}

_PATHOGEN = "Busca el material genético de este microorganismo en una muestra de heces. «Detectado» significa que se encontró."


def about(key: str) -> str | None:
    """Explicación de un análisis; None si aún no hay una escrita."""
    if key in ABOUT:
        return ABOUT[key]
    return _PATHOGEN if key.startswith("gi_") else None


def missing() -> list[str]:
    return [a.key for a in terminology.CATALOG if about(a.key) is None]
